name: Create Repo from Template
on:
  issues:
    types: [opened]

jobs:
  create-repository:
    if: startsWith(github.event.issue.title, '[Novo Projeto]')
    runs-on: ubuntu-latest
    steps:
      # 1. Log de Início
      - name: Add Start Comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ github.event.issue.number }} \
            --body "⏳ **Iniciando a configuração...** O repositório está a ser provisionado na VojoLabs."

      # 2. Lógica de Criação (com a limpeza de nome robusta)
      - name: Create Repo
        id: create_step
        env:
          GH_TOKEN: ${{ secrets.GHA_TOKEN }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          REPO_NAME=$(echo "$ISSUE_BODY" | grep -A 1 "Qual o nome do novo repositório?" | tail -n 1 | sed 's/[[:space:]]//g')
          
          if [ -z "$REPO_NAME" ] || [ "$REPO_NAME" = "_Noresponse_" ]; then
            echo "Erro: Nome vazio" && exit 1
          fi

          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          
          gh repo create "VojoLabs/$REPO_NAME" --template "VojoLabs/template-infra-aws" --public --clone
          
          cd "$REPO_NAME"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b develop
          git push origin develop

      # 3. Log de Sucesso (Só roda se tudo der certo)
      - name: Success Comment
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue close ${{ github.event.issue.number }} \
            --comment "✅ **Repositório criado!** 🔗 https://github.com/VojoLabs/${{ env.REPO_NAME }}"

      # 4. Log de Erro (Só roda se algum step anterior falhar)
      - name: Error Comment
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ github.event.issue.number }} \
            --body "❌ **Erro na configuração:** Não foi possível criar o repositório. Por favor, verifique se o nome já existe ou se as permissões do Token estão corretas."